<!DOCTYPE html><head><meta charset="UTF-8"><title>MooseException | Aurora App</title><link href="../../contrib/materialize/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"></link><link href="../../contrib/prism/prism.min.css" type="text/css" rel="stylesheet"></link><link href="../../css/moose.css" type="text/css" rel="stylesheet"></link><link href="../../css/devel_moose.css" type="text/css" rel="stylesheet"></link><link href="../../css/alert_moose.css" type="text/css" rel="stylesheet"></link><link href="../../css/content_moose.css" type="text/css" rel="stylesheet"></link><link href="../../css/sqa_moose.css" type="text/css" rel="stylesheet"></link><link href="../../css/civet_moose.css" type="text/css" rel="stylesheet"></link><script type="text/javascript" src="../../contrib/jquery/jquery.min.js"></script></head><body><div class="page-wrap"><header><nav><div class="nav-wrapper container"><a href="https://aurora-multiphysics.github.io/aurora/" class="left moose-logo hide-on-med-and-down">Aurora App</a><a href="https://github.com/aurora-multiphysics/aurora" class="right"><img src="../../media/framework/github-logo.png" class="github-mark"></img><img src="../../media/framework/github-mark.png" class="github-logo"></img></a><ul class="right hide-on-med-and-down"></ul><a href="#" class="sidenav-trigger" data-target="976e58dc-1737-4115-94df-eb9466a87f53"><i class="material-icons">menu</i></a><ul class="sidenav" id="976e58dc-1737-4115-94df-eb9466a87f53"></ul><a href="#moose-search" class="modal-trigger"><i class="material-icons">search</i></a></div></nav><div class="modal modal-fixed-footer moose-search-modal" id="moose-search"><div class="modal-content container moose-search-modal-content"><div class="row"><div class="col l12"><div class="input-field"><input type_="text" onkeyup="mooseSearch()" placeholder="https://aurora-multiphysics.github.io/aurora/" id="moose-search-box"></input></div></div><div><div class="col s12" id="moose-search-results"></div></div></div></div><div class="modal-footer"><a href="#!" class="modal-close btn-flat">Close</a></div></div></header><main class="main"><div class="container"><div class="row"><div class="col hide-on-med-and-down l12"><nav class="breadcrumb-nav"><div class="nav-wrapper"><a href=".." class="breadcrumb">source</a><span class="breadcrumb">base</span><a href="#" class="breadcrumb">MooseException</a></div></nav></div></div><div class="row"><div class="moose-content col s12 m12 l10"><section id="50d44f11-09d9-4f54-a08c-783aaffb3969" data-section-level="1" data-section-text="MooseException"><h1 id="mooseexception">MooseException</h1><p>MooseException is a normal C++ derived &quot;exception&quot; object. It&#x27;s purpose is to give developers an oppurtunity to terminate a solve, while informing MOOSE that it should perform the necessary steps to clean up the current stack, notify other threads/processors of the error and communicate with the solver that the current solve has failed. When applicable and possible, the solver will allow MOOSE to cut the time step and make another attempt at a solve.</p><p>This exception should be used directly in user code when non-fatal situations are encountered such as the inability to converge a local netwon solve in a material, or if a interpolated value from a variable or lookup table ends up out-of-range.</p><p>MOOSE is setup to catch MooseExceptions inside of several user defined callbacks that occur during the solve&#x27;s computeResidual, and computeJacobian callbacks. Note that these callbacks also include the evaluation of several other objects such as Materials, Constraints, and occasionally objects such as Postprocessors (when requested). This makes it possible to try smaller solves from most user-defined objects within MOOSE.</p><section class="scrollspy" id="3362a8b1-1ce5-405f-b618-f6c6fd0f288e" data-section-level="2" data-section-text="How it works"><h2 id="how-it-works">How it works</h2><p>MOOSE Wraps several threaded sections in PARALLEL_TRY/PARALLEL_CATCH macros (See SystemBase.h). PARALLEL_TRY does nothing (but provide scope). PARALLEL_CATCH invokes the FEProblem::checkExceptionAndStopSolve() (See FEProblemBase.h) routine after the threaded section has terminated and all threads on the same processor agree on the error status. checkExceptionAndStopSolve() then does parallel communication to ensure that all processors are notified of a single failure and cutback together. </p></section></section></div><div class="col hide-on-med-and-down l2"><div class="toc-wrapper pin-top"><ul class="section table-of-contents"><li><a href="#3362a8b1-1ce5-405f-b618-f6c6fd0f288e" class="tooltipped" data-position="left" data-tooltip="How it works">How it works</a></li></ul></div></div></div></div></main></div></body><script type="text/javascript" src="../../contrib/materialize/materialize.min.js"></script><script type="text/javascript" src="../../contrib/clipboard/clipboard.min.js"></script><script type="text/javascript" src="../../contrib/prism/prism.min.js"></script><script type="text/javascript" src="../../js/init.js"></script><script type="text/javascript" src="../../js/navigation.js"></script><script type="text/javascript" src="../../contrib/fuse/fuse.min.js"></script><script type="text/javascript" src="../../js/search_index.js"></script><script type="text/javascript" src="../../js/sqa_moose.js"></script>